### Recuperar info del pokemon dittovich
GET http://localhost:1234/pokemon/ditto

### Crear un pokemon

POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
        ]

}

### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar pelicula por id
GET http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

### Recuperar todas las peliculas por genero
GET http://localhost:3000/movies?genre=drama

###Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM users",
    "title": "MUCHACHOS",
    "year": 2023,
    "director": "Jesus Braceras",
    "duration": 108,
    "poster": "https://static.cinemarkhoyts.com.ar/Images/Posters/db41322b95ba8a3922a701287db086e2.jpg?v=00002265",
    "genre": [
        "Documental",
        "Action"
    ],
    "rate":9.6
}
###Probar un error con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": 4,
    "year": "mil 9 veitidos"    
}

### Actualizar una pelicula por id

PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "duration":140,
    "year": 1973
}